name: Find the rabbit action
description: 'Small filter action'
inputs:
  token:
    description: 'Github token'
    required: true
  needle:
    description: 'List of items to filter'
    required: true
  haystack:
    description: 'List of items to filter from'
    required: true
  key:
    description: 'Key to filter by'
    required: false
    default: 'service'
  repository:
    description: 'Repository to filter from'
    required: false
  tag:
    description: 'Override tag'
    required: false
outputs:
  filtered:
    description: 'Filtered list'
runs:
  using: 'node20'
  main: 'dist/index.js'
